### ISSUE TITLE
Error: A rest element type must be an array type.

### ISSUE THREAD

**Issue by neolitec** [sinclairzx81/typebox#40]
I have an issue with the lastest version 0.11.0:

```
node_modules/@sinclair/typebox/typebox.d.ts:6:17 - error TS2574: A rest element type must be an array type.

6     arguments: [...T];
                  ~~~~

node_modules/@sinclair/typebox/typebox.d.ts:11:17 - error TS2574: A rest element type must be an array type.

11     arguments: [...T];
                   ~~~~
```

and so on...

If I downgrade to 0.10.1, the error is not here.

Typescript version: 4.0.5

**Comment by sinclairzx81** [comment]
@neolitec Hi,

Have just tested npm package `0.11.0` against TypeScript version `4.0.5`. It seems to be working ok this side. Note, the rest / variadic stuff has recently gone in and only works with TypeScript `4.0.0` and above. I am able to replicate your issue if I downgrade to TypeScript `3.8.7` however. Maybe just double check your build process is on the latest version of the TypeScript compiler.

Let me know if this helps.

**Comment by sinclairzx81** [comment]
@neolitec I might close this issue as I can't seem to replicate the problem on TS `4.0.5`. But feel free to reopen if you're still experiencing problems. Any additional information would be helpful.

Cheers
S
